### ISSUE TITLE
Calculation of scores failed. No error json.

### ISSUE THREAD

**Issue by sjtuytc** [princeton-vl/Coupled-Iterative-Refinement#5]
`Traceback (most recent call last):  File "/mnt/proj79/zelin/dec_code/Coupled-Iterative-Refinement/additional_scripts/bop_toolkit_challenge/scripts/eval_calc_scores.py", line 244, in <module>
    scene_errs = inout.load_json(scene_errs_path, keys_to_int=True)  File "/mnt/proj79/zelin/dec_code/Coupled-Iterative-Refinement/additional_scripts/bop_toolkit_challenge/bop_toolkit_lib/inout.py", line 77, in load_json    with open(path, 'r') as f:FileNotFoundError: [Errno 2] No such file or directory: '/mnt/proj79/zelin/dec_code/Coupled-Iterative-Refinement/local_data/bop_eval_outputs/challenge2020-700290924_ycbv-test/error=vsd_ntop=-1_delta=15.000_tau=0.050/errors_000048.json'Traceback (most recent call last):  File "/mnt/proj79/zelin/dec_code/Coupled-Iterative-Refinement/additional_scripts/bop_toolkit_challenge/scripts/eval_bop19.py", line 212, in <module>
    raise RuntimeError('Calculation of scores failed.')RuntimeError: Calculation of scores failed.`

**Comment by sjtuytc** [comment]
Solved via https://vispy.org/faq.html.
