### ISSUE TITLE
environment creation fails for lietorch

### ISSUE THREAD

**Issue by JKBehrens** [princeton-vl/Coupled-Iterative-Refinement#8]
Hi,

I tried to install your code, and conda returned this error. I guess I can clone and install lietorch myself, but I wanted to leave this not for you.

Best,
Jan

```
Pip subprocess error:
  Running command git clone --quiet https://github.com/princeton-vl/lietorch.git /tmp/pip-req-build-u11m6szo
  Running command git submodule update --init --recursive -q
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-u11m6szo/setup.py", line 16, in <module>
          CUDAExtension('lietorch_backends',
        File "/home/behrejan/.conda/envs/mybase/envs/cir/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 867, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/home/behrejan/.conda/envs/mybase/envs/cir/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 975, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/home/behrejan/.conda/envs/mybase/envs/cir/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1982, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

```

**Comment by francescosarno** [comment]
I have the same issue, do you managed to solve?

**Comment by mqtjean** [comment]
Hi, 

The error here is that your CUDA_HOME environment is not set.

Do `which nvcc`

if you don't have nvcc, install cudatoolkit with the same version you build pytorch with

then redo `which nvcc`

Then if the path is for example : `/home/usr/anaconda/env_name/bin/nvcc`

Do : `export CUDA_HOME=/home/usr/anaconda/env_name/` the path without bin/nvcc
